### ISSUE TITLE
Bing: Exception: CaptchaChallenge: Use other cookies or/and ip address

### ISSUE THREAD

**Issue by Heeytch** [FujiwaraChoki/MoneyPrinterV2#13]
Traceback (most recent call last):
  File "C:\Users\highm\Desktop\MoneyPrinterV2-main\src\main.py", line 362, in <module>
    main()
  File "C:\Users\highm\Desktop\MoneyPrinterV2-main\src\main.py", line 101, in main
    youtube.generate_video(tts)
  File "C:\Users\highm\Desktop\MoneyPrinterV2-main\src\classes\YouTube.py", line 511, in generate_video
    self.generate_topic()
  File "C:\Users\highm\Desktop\MoneyPrinterV2-main\src\classes\YouTube.py", line 138, in generate_topic
    completion = self.generate_response(f"Please generate a specific video idea that takes about the following topic: {self.niche}. Make it exactly one sentence. Only return the topic, nothing else.")
  File "C:\Users\highm\Desktop\MoneyPrinterV2-main\src\classes\YouTube.py", line 111, in generate_response
    return g4f.ChatCompletion.create(
  File "C:\Users\highm\Desktop\MoneyPrinterV2-main\venv\lib\site-packages\g4f\__init__.py", line 140, in create
    return result if stream else ''.join([str(chunk) for chunk in result])
  File "C:\Users\highm\Desktop\MoneyPrinterV2-main\venv\lib\site-packages\g4f\__init__.py", line 140, in <listcomp>
    return result if stream else ''.join([str(chunk) for chunk in result])
  File "C:\Users\highm\Desktop\MoneyPrinterV2-main\venv\lib\site-packages\g4f\Provider\retry_provider.py", line 65, in create_completion
    self.raise_exceptions()
  File "C:\Users\highm\Desktop\MoneyPrinterV2-main\venv\lib\site-packages\g4f\Provider\retry_provider.py", line 114, in raise_exceptions
    raise RetryProviderError("RetryProvider failed:\n" + "\n".join([
g4f.errors.RetryProviderError: RetryProvider failed:
Liaobots: ClientResponseError: 401, message='Unauthorized', url=URL('https://liaobots.work/api/user')
Bing: Exception: CaptchaChallenge: Use other cookies or/and ip address

**Comment by Heeytch** [comment]
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/160403469/bd94deb7-4fa2-409b-9c5d-eab56d2e17f4)

Change "llm" and "image_prompt_llm" to fix this.
