### ISSUE TITLE
Error when running on Mac

### ISSUE THREAD

**Issue by s4-hub** [FujiwaraChoki/MoneyPrinterV2#15]
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/57908082/80aae8c1-45e1-493d-8124-7f25cdb60889)

Hi. I got error when running on Mac.
What should i do ?

**Comment by FujiwaraChoki** [comment]
Your firefox path is incorrect.

**Comment by margox** [comment]
> Your firefox path is incorrect.

Could you show us a correct firefox profile path example?

**Comment by s4-hub** [comment]
> > Your firefox path is incorrect.
> 
> Could you show us a correct firefox profile path example?

"firefox_profile": "/Users/yagami_ai/Library/Application Support/Firefox/Profiles/p4cq53t0.default"
this is my firefox profile path

**Comment by neilk17** [comment]
"firefox_profile": "Users/neil/Library/Application Support/Firefox/Profiles/xxx.default"

```Traceback (most recent call last):
  File "/Users/neil/apps/MoneyPrinterV2/src/main.py", line 377, in <module>
    main()
  File "/Users/neil/apps/MoneyPrinterV2/src/main.py", line 92, in main
    youtube = YouTube(
  File "/Users/neil/apps/MoneyPrinterV2/src/classes/YouTube.py", line 83, in __init__
    self.browser: webdriver.Firefox = webdriver.Firefox(service=self.service, options=self.options)
  File "/Users/neil/apps/MoneyPrinterV2/venv/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/Users/neil/apps/MoneyPrinterV2/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/Users/neil/apps/MoneyPrinterV2/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/Users/neil/apps/MoneyPrinterV2/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/Users/neil/apps/MoneyPrinterV2/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Failed to set preferences: unknown error
```
I used this as my firefox profile but I'm still getting the same error on Mac. What am I missing?
