### ISSUE TITLE
firefox profile

### ISSUE THREAD

**Issue by InternalShadow** [FujiwaraChoki/MoneyPrinterV2#31]
With this config.json I am getting the below error
<p><h4>config.json</h4><code>
{
  "verbose": true,
  "firefox_profile": "C:\\Users\\mikey\\AppData\\Local\\Mozilla\\Firefox\\Profiles\\40n7xz2q.dev-edition-default",
  "headless": false,
  "twitter_language": "English",
  "llm": "gpt4",
  "image_prompt_llm": "gpt4",
  "image_model": "v3",
  "threads": 2,
  "zip_url": "",
  "is_for_kids": false,
  "google_maps_scraper": "https://github.com/gosom/google-maps-scraper/archive/refs/tags/v0.9.7.zip",
  "email": {
    "smtp_server": "smtp.gmail.com",
    "smtp_port": 587,
    "username": "",
    "password": ""
  },
  "google_maps_scraper_niche": "",
  "scraper_timeout": 300,
  "outreach_message_subject": "I have a question...",
  "outreach_message_body_file": "outreach_message.html",
  "assembly_ai_api_key": "1234567890sdfghjk6789",
  "font": "bold_font.ttf",
  "imagemagick_path": "C:\\Program Files\\ImageMagick-7.1.1-Q16-HDRI\\magick.exe"
}

</code>
</p>

![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/76181682/40cef727-893f-48e1-b058-48ee94723e5b)
<p>
<h4>Error along with stacktrace</h4>
<code>
Traceback (most recent call last):
  File "C:\Users\mikey\Desktop\Projects\MoneyPrinterV2\src\main.py", line 364, in <module>
    main()
  File "C:\Users\mikey\Desktop\Projects\MoneyPrinterV2\src\main.py", line 79, in main
    youtube = YouTube(
  File "C:\Users\mikey\Desktop\Projects\MoneyPrinterV2\src\classes\YouTube.py", line 83, in __init__
    self.browser: webdriver.Firefox = webdriver.Firefox(service=self.service, options=self.options)
  File "C:\Users\mikey\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\mikey\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\mikey\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\mikey\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\mikey\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
</code></p>

**Comment by FujiwaraChoki** [comment]
Show us `.mp/youtube.json`

**Comment by FujiwaraChoki** [comment]
Make sure every firefox window is closed before starting MPV2.

**Comment by InternalShadow** [comment]
All firefox windows are closed before running mpv2 still same issue

**Comment by InternalShadow** [comment]
Does it have to do with firefox-dev vs firefox base and the selenium webdriver version compatibilities?
