### ISSUE TITLE
RuntimeError: Incorrect response

### ISSUE THREAD

**Issue by glowly112** [FujiwaraChoki/MoneyPrinterV2#47]
I seem to be getting the below issue when i run the code, it looks like the code is having issues producing any of the ouputs

 Discriminator Model: univnet_discriminator
⚠️ Generated Title is too long. Retrying...
⚠️ Generated Title is too long. Retrying...
⚠️ Generated Title is too long. Retrying...
⚠️ GPT returned an unformatted response. Attempting to clean...
⚠️ Failed to generate Image Prompts. Retrying...
⚠️ GPT returned an unformatted response. Attempting to clean...
⚠️ Failed to generate Image Prompts. Retrying...
Traceback (most recent call last):
  File "C:\Users\Home\PycharmProjects\MoneyPrinterV2\src\classes\YouTube.py", line 267, in generate_prompts
    image_prompts = json.loads(completion)
  File "C:\Users\Home\anaconda3\envs\MoneyPrinterV2\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Home\anaconda3\envs\MoneyPrinterV2\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Home\anaconda3\envs\MoneyPrinterV2\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 10555 (char 10554)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Home\PycharmProjects\MoneyPrinterV2\src\classes\YouTube.py", line 267, in generate_prompts
    image_prompts = json.loads(completion)
  File "C:\Users\Home\anaconda3\envs\MoneyPrinterV2\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Home\anaconda3\envs\MoneyPrinterV2\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Home\anaconda3\envs\MoneyPrinterV2\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 66 column 1 (char 5354)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Home\PycharmProjects\MoneyPrinterV2\src\main.py", line 364, in <module>
    main()
  File "C:\Users\Home\PycharmProjects\MoneyPrinterV2\src\main.py", line 101, in main
    youtube.generate_video(tts)
  File "C:\Users\Home\PycharmProjects\MoneyPrinterV2\src\classes\YouTube.py", line 528, in generate_video
    self.generate_prompts()
  File "C:\Users\Home\PycharmProjects\MoneyPrinterV2\src\classes\YouTube.py", line 280, in generate_prompts
    return self.generate_prompts()
  File "C:\Users\Home\PycharmProjects\MoneyPrinterV2\src\classes\YouTube.py", line 280, in generate_prompts
    return self.generate_prompts()
  File "C:\Users\Home\PycharmProjects\MoneyPrinterV2\src\classes\YouTube.py", line 257, in generate_prompts
    completion = str(self.generate_response(prompt, model=parse_model(get_image_prompt_llm())))\
  File "C:\Users\Home\PycharmProjects\MoneyPrinterV2\src\classes\YouTube.py", line 126, in generate_response
    return g4f.ChatCompletion.create(
  File "C:\Users\Home\anaconda3\envs\MoneyPrinterV2\lib\site-packages\g4f\__init__.py", line 146, in create
    return result if stream else ''.join([str(chunk) for chunk in result])
  File "C:\Users\Home\anaconda3\envs\MoneyPrinterV2\lib\site-packages\g4f\__init__.py", line 146, in <listcomp>
    return result if stream else ''.join([str(chunk) for chunk in result])
  File "C:\Users\Home\anaconda3\envs\MoneyPrinterV2\lib\site-packages\g4f\providers\retry_provider.py", line 79, in create_completion
    raise e
  File "C:\Users\Home\anaconda3\envs\MoneyPrinterV2\lib\site-packages\g4f\providers\retry_provider.py", line 69, in create_completion
    for token in provider.create_completion(model, messages, stream, **kwargs):
  File "C:\Users\Home\anaconda3\envs\MoneyPrinterV2\lib\site-packages\g4f\providers\base_provider.py", line 204, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
  File "C:\Users\Home\anaconda3\envs\MoneyPrinterV2\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Home\anaconda3\envs\MoneyPrinterV2\lib\site-packages\g4f\providers\base_provider.py", line 200, in await_callback
    return await callback()
  File "C:\Users\Home\anaconda3\envs\MoneyPrinterV2\lib\site-packages\g4f\Provider\ChatBase.py", line 60, in create_async_generator
    raise RuntimeError("Incorrect response")
RuntimeError: Incorrect response

**Comment by FujiwaraChoki** [comment]
Issue with `g4f`
