### ISSUE TITLE
Issue regarding what seems to be TTS

### ISSUE THREAD

**Issue by ZigZagBoi1** [FujiwaraChoki/MoneyPrinterV2#52]
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/66926735/51df64dd-2f46-4081-bdda-ce0180ddd3e2)

Traceback (most recent call last):
  File "C:\Users\marwa\Desktop\MoneyPrinterV2-main\src\main.py", line 364, in <module>
    main()
  File "C:\Users\marwa\Desktop\MoneyPrinterV2-main\src\main.py", line 98, in main
    tts = TTS()
  File "C:\Users\marwa\Desktop\MoneyPrinterV2-main\src\classes\Tts.py", line 29, in __init__
    self._model_manager = ModelManager(models_json_path)
  File "C:\Users\marwa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\TTS\utils\manage.py", line 56, in __init__
    self.read_models_file(models_file)
  File "C:\Users\marwa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\TTS\utils\manage.py", line 68, in read_models_file
    self.models_dict = read_json_with_comments(file_path)
  File "C:\Users\marwa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\TTS\config\__init__.py", line 17, in read_json_with_comments
    with fsspec.open(json_path, "r", encoding="utf-8") as f:
  File "C:\Users\marwa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fsspec\core.py", line 103, in __enter__
    f = self.fs.open(self.path, mode=mode)
  File "C:\Users\marwa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fsspec\spec.py", line 1293, in open
    f = self._open(
  File "C:\Users\marwa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fsspec\implementations\local.py", line 184, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "C:\Users\marwa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fsspec\implementations\local.py", line 306, in __init__
    self._open()
  File "C:\Users\marwa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fsspec\implementations\local.py", line 311, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/marwa/Desktop/MoneyPrinterV2-main/venv/Lib/site-packages/TTS/.models.json'

**Comment by ZigZagBoi1** [comment]
this is for the youtube shorts btw

**Comment by ZigZagBoi1** [comment]
Hey! Solved!

so when you install TTS, it installs to the default python directory, just go there and find the (TTS) file copy that over into the venv\lib\site-packages\

and boom it should work :D
