### ISSUE TITLE
ValueError: Please provide an API key via the ASSEMBLYAI_API_KEY environment variable or the global settings.

### ISSUE THREAD

**Issue by Heeytch** [FujiwaraChoki/MoneyPrinterV2#7]
✅  => Chose song: 1-minute-of-silence.zip
Traceback (most recent call last):
  File "C:\Users\highm\Desktop\MoneyPrinterV2-main\src\main.py", line 362, in <module>
    main()
  File "C:\Users\highm\Desktop\MoneyPrinterV2-main\src\main.py", line 101, in main
    youtube.generate_video(tts)
  File "C:\Users\highm\Desktop\MoneyPrinterV2-main\src\classes\YouTube.py", line 530, in generate_video
    path = self.combine()
  File "C:\Users\highm\Desktop\MoneyPrinterV2-main\src\classes\YouTube.py", line 468, in combine
    subtitles_path = self.generate_subtitles(self.tts_path)
  File "C:\Users\highm\Desktop\MoneyPrinterV2-main\src\classes\YouTube.py", line 397, in generate_subtitles
    transcriber = aai.Transcriber(config=config)
  File "C:\Users\highm\Desktop\MoneyPrinterV2-main\venv\lib\site-packages\assemblyai\transcriber.py", line 823, in __init__
    self._client = client or _client.Client.get_default()
  File "C:\Users\highm\Desktop\MoneyPrinterV2-main\venv\lib\site-packages\assemblyai\client.py", line 88, in get_default
    cls._default = cls(
  File "C:\Users\highm\Desktop\MoneyPrinterV2-main\venv\lib\site-packages\assemblyai\client.py", line 32, in __init__
    raise ValueError(
ValueError: Please provide an API key via the ASSEMBLYAI_API_KEY environment variable or the global settings.

**Comment by FujiwaraChoki** [comment]
Fill out values in example config.
