### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException: Message: Failed to set preferences: unknown error

### ISSUE THREAD

**Issue by agusmakmun** [FujiwaraChoki/MoneyPrinterV2#84]
Hello I'm getting this error while using it:

```python
MoneyPrinterV2 git:(main) ✗ python src/main.py

  __  __                        _____      _       _             __      _____
 |  \/  |                      |  __ \    (_)     | |            \ \    / /__ \
 | \  / | ___  _ __   ___ _   _| |__) | __ _ _ __ | |_ ___ _ __   \ \  / /   ) |
 | |\/| |/ _ \| '_ \ / _ \ | | |  ___/ '__| | '_ \| __/ _ \ '__|   \ \/ /   / /
 | |  | | (_) | | | |  __/ |_| | |   | |  | | | | | ||  __/ |       \  /   / /_
 |_|  |_|\___/|_| |_|\___|\__, |_|   |_|  |_|_| |_|\__\___|_|        \/   |____|
                           __/ |
                          |___/

ℹ️  => Fetching songs...

============ OPTIONS ============
 1. YouTube Shorts Automation
 2. Twitter Bot
 3. Affiliate Marketing
 4. Outreach
 5. Quit
 =================================

Select an option: 1
ℹ️ Starting YT Shorts Automater...
+----+--------------------------------------+----------+---------+
| ID |                 UUID                 | Nickname |  Niche  |
+----+--------------------------------------+----------+---------+
| 1  | c6ceb73b-16f3-489d-83f5-xxxx |  xxx  | @xxx |
+----+--------------------------------------+----------+---------+
❓ Select an account to start: 1
Traceback (most recent call last):
  File "/Users/myname/envs/env-affiliate-automation/MoneyPrinterV2/src/main.py", line 377, in <module>
    main()
  File "/Users/myname/envs/env-affiliate-automation/MoneyPrinterV2/src/main.py", line 92, in main
    youtube = YouTube(
  File "/Users/myname/envs/env-affiliate-automation/MoneyPrinterV2/src/classes/YouTube.py", line 83, in __init__
    self.browser: webdriver.Firefox = webdriver.Firefox(service=self.service, options=self.options)
  File "/Users/myname/envs/env-affiliate-automation/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 67, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/Users/myname/envs/env-affiliate-automation/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/Users/myname/envs/env-affiliate-automation/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/Users/myname/envs/env-affiliate-automation/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Users/myname/envs/env-affiliate-automation/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Failed to set preferences: unknown error
```

**Comment by neilk17** [comment]
I have the same error

**Comment by Felos9001** [comment]
same error here too

**Comment by techydad05** [comment]
Same here.. anyone resolve this?

**Comment by prxshetty** [comment]
Try to put your mozilla firefox profile in the config files for YT / Twitter. 
Or remove the .mp file that was created when you first launched the app.py. this should resolve it.
